"""add blocked fields to content_sources

Revision ID: 20260407
Revises: 20260402
Create Date: 2026-04-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260407'
down_revision: Union[str, None] = '20260402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_sources', sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('content_sources', sa.Column('blocked_reason', sa.String(length=255), nullable=True))
    op.create_index('idx_source_blocked', 'content_sources', ['is_blocked'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_blocked', 'content_sources')
    op.drop_column('content_sources', 'blocked_reason')
    op.drop_column('content_sources', 'is_blocked')
    # ### end Alembic commands ###
