"""01_add_new_tables_and_fields

Revision ID: 26bf7e5b8c8d
Revises: 8ff9788030e6
Create Date: 2026-02-12 15:18:20.971690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bf7e5b8c8d'
down_revision: Union[str, Sequence[str], None] = '8ff9788030e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
