"""Add Creator_Id_Manage_Group

Revision ID: 38ea512627f8
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 10:51:42.284966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ea512627f8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_groups', sa.Column('creator_id', sa.BigInteger(), nullable=True))
    op.create_index('idx_group_creator', 'managed_groups', ['creator_id'], unique=False)
    op.create_foreign_key(None, 'managed_groups', 'telegram_accounts', ['creator_id'], ['telegram_account_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managed_groups', type_='foreignkey')
    op.drop_index('idx_group_creator', table_name='managed_groups')
    op.drop_column('managed_groups', 'creator_id')
    # ### end Alembic commands ###
