"""22_02_REFACT_DB_2

Revision ID: 6bc2b5e60ea3
Revises: 31ff718b59e7
Create Date: 2026-02-22 10:48:16.089375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc2b5e60ea3'
down_revision: Union[str, Sequence[str], None] = '31ff718b59e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_sources', 'title')
    op.drop_column('content_sources', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_sources', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content_sources', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
