"""Add YouTube HTML parser fields

Revision ID: 84afe9f39976
Revises: 9024ccdbccaf
Create Date: 2026-02-17 10:22:54.371170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84afe9f39976'
down_revision: Union[str, Sequence[str], None] = '9024ccdbccaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_sources', sa.Column('youtube_username', sa.String(length=100), nullable=True))
    op.add_column('content_sources', sa.Column('last_video_timestamp', sa.BigInteger(), nullable=True))
    op.add_column('content_sources', sa.Column('channel_language', sa.String(length=10), nullable=True))
    op.create_index('idx_last_video_timestamp', 'content_sources', ['last_video_timestamp'], unique=False)
    op.create_index('idx_youtube_username', 'content_sources', ['youtube_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_youtube_username', table_name='content_sources')
    op.drop_index('idx_last_video_timestamp', table_name='content_sources')
    op.drop_column('content_sources', 'channel_language')
    op.drop_column('content_sources', 'last_video_timestamp')
    op.drop_column('content_sources', 'youtube_username')
    # ### end Alembic commands ###
