"""add_last_video_id

Revision ID: 9024ccdbccaf
Revises: f480ac908ac5
Create Date: 2026-02-14 13:42:45.581038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9024ccdbccaf'
down_revision: Union[str, Sequence[str], None] = 'f480ac908ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_sources', sa.Column('last_video_id', sa.String(length=100), nullable=True))
    op.create_index('idx_source_last_video', 'content_sources', ['last_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_last_video', table_name='content_sources')
    op.drop_column('content_sources', 'last_video_id')
    # ### end Alembic commands ###
