"""22_02_REFACT_DB_3_add_display_name

Revision ID: c8eb4f8face9
Revises: 6bc2b5e60ea3
Create Date: 2026-02-22 15:59:28.630166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8eb4f8face9'
down_revision: Union[str, Sequence[str], None] = '6bc2b5e60ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_sources', sa.Column('channel_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_sources', 'channel_title')
    # ### end Alembic commands ###
